AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Room Booking System Backend with Email Notification

Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Resources:
  BookingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin,Accept,Access-Control-Allow-Origin'"
        AllowOrigin: "'*'"

  BookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs16.x
      Environment:
        Variables:
          ROOM1_TABLE: !Ref QMB1
          ROOM2_TABLE: !Ref QMB2
          CANCEL_URL: "https://main.d16zph37xouq67.amplifyapp.com/"  # Change this to your actual frontend domain
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref QMB1
        - DynamoDBCrudPolicy:
            TableName: !Ref QMB2
        - Statement:
            Effect: Allow
            Action:
              - "ses:SendEmail"
              - "ses:SendRawEmail"
            Resource: "*"
      Events:
        CancelBooking:
          Type: Api
          Properties:
            Path: /cancelBooking
            Method: get
            RestApiId: !Ref BookingApi
        GetSlots:
          Type: Api
          Properties:
            Path: /getSlots
            Method: get
            RestApiId: !Ref BookingApi
        GetAvailableSlots:
          Type: Api
          Properties:
            Path: /getAvailableSlots
            Method: get
            RestApiId: !Ref BookingApi
        BookSlot:
          Type: Api
          Properties:
            Path: /bookSlot
            Method: post
            RestApiId: !Ref BookingApi
        Options:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: options
            RestApiId: !Ref BookingApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

  # DynamoDB Table for Room 1
  QMB1:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QMB1
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: BookingID
          AttributeType: N
        - AttributeName: Date
          AttributeType: S
        - AttributeName: CancellationToken
          AttributeType: S
      KeySchema:
        - AttributeName: BookingID
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CancellationToken-index
          KeySchema:
            - AttributeName: CancellationToken
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # DynamoDB Table for Room 2
  QMB2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QMB2
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: BookingID
          AttributeType: N
        - AttributeName: Date
          AttributeType: S
        - AttributeName: CancellationToken
          AttributeType: S
      KeySchema:
        - AttributeName: BookingID
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CancellationToken-index
          KeySchema:
            - AttributeName: CancellationToken
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  BookingApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${BookingApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
